- LICENSE
Hi @slapperwan, :smile:
I **add the year** and **the name of the copyright owner** *for this project* in the **`LICENSE`** file. :pencil2:
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:
> Add year and name of copyright owner

- res/layout/issue_comment_list_header.xml
- res/values/strings.xml
- src/com/gh4a/activities/IssueActivity.java
- src/com/gh4a/fragment/PullRequestFragment.java
> Display no description text for pull requests and issues without one

- res/values/strings.xml
- src/com/gh4a/adapter/IssueEventAdapter.java
- src/com/gh4a/loader/IssueCommentListLoader.java
- src/com/gh4a/loader/IssueEventHolder.java
- src/com/gh4a/loader/PullRequestCommentListLoader.java
> Fix pull reqest events mentioning "Issue" instead of "Pull request"

- src/com/gh4a/fragment/TrendingFragment.java
- src/com/gh4a/loader/TrendLoader.java
changes in TrendingFragment got lost in ce98bad
> Really fix trend loading

- src/com/gh4a/fragment/CommentBoxFragment.java
> Fix comment send button being enabled when text is empty

- src/com/gh4a/BaseActivity.java
> Do not animate drawer toggle icon

- res/menu/issue_menu.xml
- res/menu/pullrequest_menu.xml
- src/com/gh4a/activities/IssueActivity.java
- src/com/gh4a/activities/PullRequestActivity.java
> Add action to open issue/pull request in browser

- src/com/gh4a/BaseActivity.java
- src/com/gh4a/activities/home/HomeActivity.java
> Fix initial item highlight in navigation drawer

- res/layout/list_fragment_content.xml
- src/com/gh4a/fragment/LoadingListFragmentBase.java
> Fix toolbar collapsing when there are no items

- res/menu/issue_list_filter.xml
- res/menu/issue_list_filter_collab.xml
- res/values/arrays.xml
- res/values/strings.xml
- src/com/gh4a/activities/IssueListActivity.java
- src/com/gh4a/activities/home/IssueListFactory.java
Added both as a tab in "My issues" screen and a filter for repository's issues list.
Closes #349.
> Issue participating status filter

- res/values/strings.xml
- src/com/gh4a/activities/RepositoryActivity.java
- src/com/gh4a/fragment/RepositoryEventListFragment.java
> Add repository activity tab

- res/layout/issue_header.xml
- src/com/gh4a/activities/IssueActivity.java
- src/com/gh4a/activities/PullRequestActivity.java
> Place issue title in HorizontalScrollView

- res/menu/repo_menu.xml
- src/com/gh4a/BaseActivity.java
- src/com/gh4a/activities/Github4AndroidActivity.java
- src/com/gh4a/activities/RepositoryActivity.java
- src/com/gh4a/activities/SearchActivity.java
- src/com/gh4a/activities/home/HomeActivity.java
> Add search action to repository screen

- src/com/gh4a/activities/IssueEditActivity.java
> Navigate to correct parent from issue edit screen

- src/com/gh4a/activities/IssueMilestoneEditActivity.java
> Navigate to milestones list when going up from edit milestone

- src/com/gh4a/activities/IssueListActivity.java
> Fix closed issues not loading

- src/com/gh4a/activities/IssueMilestoneEditActivity.java
null value doesn't make hasExtra() return false
> Fix milestone creation not working

- res/menu/edit_milestone_menu.xml
- res/values/strings.xml
- src/com/gh4a/activities/IssueMilestoneEditActivity.java
- src/com/gh4a/utils/ApiHelpers.java
> Add actions to close/reopen milestone

- res/values/strings.xml
- src/com/gh4a/activities/IssueMilestoneListActivity.java
- src/com/gh4a/fragment/IssueMilestoneListFragment.java
- src/com/gh4a/loader/MilestoneListLoader.java
> Display closed milestones in milestone list

- src/com/gh4a/activities/GistViewerActivity.java
- src/com/gh4a/utils/HtmlUtils.java
This patchset deals with some of the Lint warnings, there are many more to resolve though.
I think it would make sense to adress all warnings in time, to avoid mountains of required overhauls in the future.
> Lint fixes

- src/com/gh4a/activities/CommitDiffViewerActivity.java
- src/com/gh4a/activities/DiffViewerActivity.java
- src/com/gh4a/activities/PullRequestDiffViewerActivity.java
> Correctly link pull request files

- .idea/codeStyleSettings.xml
- build.gradle
- res/layout/generic_list.xml
- res/values/attrs.xml
- res/values/colors.xml
- res/values/themes.xml
- src/com/gh4a/fragment/LoadingListFragmentBase.java
> Fast scroller

- src/com/gh4a/BrowseFilter.java
> Handle issue creation links

- res/values/strings.xml
- src/com/gh4a/activities/RepositoryActivity.java
- src/com/gh4a/fragment/PullRequestFragment.java
- src/com/gh4a/utils/UiUtils.java
Now you can click on the from and into branches of pull requests to open repository view for them.
Closes #543
> Add option to view pull request branches

- src/com/gh4a/BrowseFilter.java
> Only open blog list activity if not linking directly to article

- res/menu/repo_menu.xml
- res/menu/user_menu.xml
- src/com/gh4a/activities/RepositoryActivity.java
- src/com/gh4a/activities/UserActivity.java
> Add open in browser action for repository and user

- res/layout/issue_create.xml
- src/com/gh4a/activities/IssueEditActivity.java
- src/com/gh4a/fragment/IssueFragmentBase.java
- src/com/gh4a/utils/UiUtils.java
Changed them so they appear just like when viewing the issue:
- Labels are colored
- Assignees display avatars
> Improve appearance of labels and assignees in issue edit activity 

- res/values/strings.xml
- src/com/gh4a/activities/RepositoryActivity.java
- src/com/gh4a/activities/UserActivity.java
- src/com/gh4a/db/BookmarksProvider.java
Closes #557.
Probably can also close #296 as with this change it won't be possible to create duplicates anymore. (And fast scroll is implemented too)
> Make bookmark action work as toggle

- src/com/gh4a/BrowseFilter.java
- src/com/gh4a/activities/CommitActivity.java
- src/com/gh4a/activities/CommitDiffViewerActivity.java
- src/com/gh4a/activities/DiffViewerActivity.java
- src/com/gh4a/activities/IssueActivity.java
- src/com/gh4a/activities/PullRequestActivity.java
- src/com/gh4a/activities/PullRequestDiffViewerActivity.java
- src/com/gh4a/fragment/BookmarkListFragment.java
- src/com/gh4a/fragment/CommitFragment.java
- src/com/gh4a/fragment/CommitNoteFragment.java
- src/com/gh4a/fragment/EventListFragment.java
- src/com/gh4a/fragment/IssueFragment.java
- src/com/gh4a/fragment/IssueFragmentBase.java
- src/com/gh4a/fragment/NotificationListFragment.java
- src/com/gh4a/fragment/PullRequestFragment.java
- src/com/gh4a/utils/IntentUtils.java
The API doesn't tell the id of that comment so instead I'm finding a comment based on the date when the issue was last viewed.
> Scroll to first unread comment when coming from notification

- res/layout/issue_create_header.xml
> Auto-capitalize text in issue title input field

- src/com/gh4a/adapter/NotificationAdapter.java
Needs testing because I ran out of notifications.
> Mark repository as read when marking last unread notification

- app/src/main/java/com/gh4a/activities/home/HomeActivity.java
- app/src/main/res/layout/drawer_header_left.xml
Added click highlight again and fixed bottom padding.
> Drawer header improvements

- app/src/main/res/layout/row_repo.xml
> Make repository attributes scrollable

- app/src/main/java/com/gh4a/fragment/CommitFragment.java
- app/src/main/res/layout/commit.xml
> Make links in commit messages clickable

- app/build.gradle
- app/src/main/java/com/gh4a/adapter/EventAdapter.java
- app/src/main/java/com/gh4a/fragment/CommitFragment.java
- app/src/main/java/com/gh4a/fragment/RepositoryFragment.java
Affected places:
- Commit messages
- Activity events
- Repository descriptions
Closes #584
> Render emoji using separate library where necessary

- app/src/main/java/com/gh4a/adapter/RepositoryAdapter.java
- app/src/main/res/layout/row_repo.xml
Fixes an issue introduced in 76f9ebea89c90c3085052a397f7fe6a135af7f3b where when clicking on repository attributes no longer opened the repository.
> Fix being unable to open repo when clicking on attributes

- app/src/main/java/com/gh4a/BrowseFilter.java
- app/src/main/java/com/gh4a/fragment/EventListFragment.java
I feel like now all of these load tasks should be moved out of `BrowseFilter` to separate file(s).
> Directly open and highlight comment from news feed

- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/activities/WebViewerActivity.java
- app/src/main/res/menu/file_viewer_menu.xml
- app/src/main/res/values/strings.xml
A small feature that I needed. Allows you to see a raw content of any markdown file:
> Add a way to view raw content of markdown files

- app/src/main/java/com/gh4a/activities/RepositoryActivity.java
- app/src/main/java/com/gh4a/activities/UserActivity.java
- app/src/main/java/com/gh4a/fragment/UserFragment.java
- app/src/main/res/menu/repo_menu.xml
- app/src/main/res/menu/user_follow_menu.xml
- app/src/main/res/menu/user_menu.xml
- app/src/main/res/values/strings.xml
> Disable follow action for organizations

- app/src/main/java/com/gh4a/activities/home/HomeActivity.java
- app/src/main/java/com/gh4a/fragment/RepositoryFragment.java
- app/src/main/res/drawable/drop_down_arrow_dark.xml
- app/src/main/res/drawable/drop_down_arrow_white.xml
- app/src/main/res/drawable/drop_up_arrow.xml
- app/src/main/res/drawable/drop_up_arrow_dark.xml
- app/src/main/res/drawable/drop_up_arrow_white.xml
- app/src/main/res/layout/drawer_header_left.xml
- app/src/main/res/layout/repository.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/themes.xml
> Make README collapsible

- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- github-api/src/main/java/org/eclipse/egit/github/core/service/IssueService.java
> When editing issue only update changed properties

- app/src/main/java/com/gh4a/adapter/timeline/DiffViewHolder.java
- app/src/main/res/layout/row_timeline_diff.xml
@Tunous Thoughts? I'm unsure whether to do this or to just make the diff font a little smaller; it's currently a bit large for my taste.
> Use code viewer text size setting for diff view in review.

- app/src/main/java/com/gh4a/adapter/timeline/CommentViewHolder.java
- app/src/main/res/values/strings.xml
- github-api/src/main/java/org/eclipse/egit/github/core/Comment.java
> Display author association next to username

- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
- app/src/main/java/com/gh4a/fragment/PullRequestFragment.java
- app/src/main/java/com/gh4a/widget/PullRequestBranchInfoView.java
- app/src/main/res/layout/issue_comment_list_header.xml
- app/src/main/res/layout/view_pull_request_branch_info.xml
- app/src/main/res/menu/pull_request_fragment_menu.xml
- app/src/main/res/menu/pullrequest_menu.xml
- Deleted branches are no longer clickable
- Branch action is removed if pull request is still open (Closes #750)
- Improved click highlights for individual branches
> Branch deletion improvements

- app/src/main/java/com/gh4a/adapter/timeline/EventViewHolder.java
- app/src/main/java/com/gh4a/adapter/timeline/ReviewViewHolder.java
- app/src/main/java/com/gh4a/utils/StringUtils.java
- app/src/main/java/com/gh4a/widget/TimestampToastSpan.java
- app/src/main/res/values/strings.xml
> Update timeline events formatting

- app/src/main/java/com/gh4a/adapter/timeline/ReplyViewHolder.java
- app/src/main/java/com/gh4a/adapter/timeline/TimelineItemAdapter.java
- app/src/main/java/com/gh4a/fragment/IssueFragment.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/PullRequestFragment.java
- app/src/main/java/com/gh4a/fragment/ReviewFragment.java
- app/src/main/java/com/gh4a/loader/ReviewTimelineLoader.java
- app/src/main/java/com/gh4a/loader/TimelineItem.java
- app/src/main/java/com/gh4a/widget/CommentEditor.java
- app/src/main/java/com/gh4a/widget/EditorBottomSheet.java
- app/src/main/res/values/strings.xml
Additionally fixed comments not refreshing after adding new one. (Closes #722)
> Use in-screen bottom sheet for review replies

- app/src/main/java/com/gh4a/adapter/TrendAdapter.java
- app/src/main/java/com/gh4a/model/Trend.java
- app/src/main/res/layout/row_trend.xml
reorder as on github.com/trending
> add language to trending page

- app/build.gradle
- app/src/main/java/com/gh4a/utils/HttpImageGetter.java
http://bigbadaboom.github.io/androidsvg/release-1.3.html
> Bump androidsvg from 1.2.2-beta-1 to 1.3

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gh4a/Gh4Application.java
See
https://github.com/robolectric/robolectric/issues/4788#issuecomment-494152278
and
https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration#on-demand
Probably improves startup performance too.
> Initialize work manager on demand to fix tests

- .gitignore
- README.md
- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- app/src/main/java/com/gh4a/fragment/SearchFragment.java
- app/src/main/java/com/gh4a/utils/CustomTabsHelper.java
- gradle.properties
Fix a few lint errors while at it.
> Complete AndroidX migration

- app/src/main/java/com/gh4a/BaseActivity.java
- app/src/main/java/com/gh4a/activities/CommitActivity.java
- app/src/main/java/com/gh4a/activities/IssueActivity.java
- app/src/main/java/com/gh4a/activities/IssueListActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
See https://twitter.com/yrezgui/status/1416673883437113350
> Provide content assists for sharing URLs

- app/src/main/java/com/gh4a/fragment/FollowersFollowingListFragment.java
> Fix "Follow" action being displayed instead of "Unfollow" in followers list

- README.md
- app/src/main/java/com/gh4a/fragment/SettingsFragment.java
It's been about two years since that library was dropped.
> Remove Android-Job from used libraries and add AndroidX instead

- app/src/main/java/com/gh4a/ServiceFactory.java
- app/src/main/java/com/gh4a/fragment/LoginModeChooserFragment.java
- app/src/main/res/layout/login_dialog.xml
- app/src/main/res/values/strings.xml
- metadata/en-US/full_description.txt
GitHub already [deprecated and removed it more than one year ago](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/).
Therefore it was just a broken feature :)
Closes #1056
> Remove login with username/password

- app/src/main/java/com/gh4a/fragment/SettingsFragment.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
https://developer.chrome.com/docs/android/custom-tabs/best-practices/#allow-the-user-to-opt-out-of-custom-tabs
> Add a setting to disable custom tabs
