slapperwan/gh4a

- src/com/gh4a/activities/IssueListActivity.java
The `mCreateFab` member is only set when authorized.
Fixes #319.
> Fix NPE in IssueListActivity when not authorized

- src/com/gh4a/activities/IssueLabelListActivity.java
- src/com/gh4a/adapter/IssueLabelAdapter.java
Before this change when user canceled changing label properties the color wouldn't be restored to its previous value. Instead, it would stay displayed with the change color.
This commit fixes this by resetting editedColor and editedName to their default values when label editing is stopped.
> Restore original label properties when cancelling label edit

- AndroidManifest.xml
While the theme is set programmatically for each activity it is helpful to also define default theme for application in the AndroidManifest file. Doing so tells Android Studio to use this theme when looking at the layout preview. Without that Android Studio uses incorrect theme which requires to change it manually each time to be able to see correct preview and avoid errors.
> Set default application theme

- src/com/gh4a/activities/home/NewsFeedFactory.java
The `position == 0` is used for viewing user activity which makes it necessary to distract 1 from the position when attempting to retrieve correct organization
> Fix off by one error for organization selection

- res/menu/repo_menu.xml
- res/values/strings.xml
Simply calling the action "Search" is a bit too broad since it doesn't specify exactly what the user would be searching for. Is it issues, code, content of readme, files?
This commit fixes the issue by making the action exactly specify what it can be used to search for, which is "Search code".
> Change title of search action in repository activity

- src/com/gh4a/activities/IssueEditActivity.java
- src/com/gh4a/activities/IssueLabelListActivity.java
- src/com/gh4a/activities/IssueMilestoneEditActivity.java
- src/com/gh4a/activities/IssueMilestoneListActivity.java
- src/com/gh4a/fragment/IssueMilestoneListFragment.java
This commits adds neutral buttons to the dialogs displayed in the issue edit activity when selecting labels or milestones. Pressing on these buttons opens corresponding screens and if something is modified by the user they notify the calling activities to reload the data.
To implement this change I had to make a small modification in the `IssueMilestoneEditActivity`. It now uses the `finish()` method after successfull actions instead of starting new issue list activity. This is the same behavior as the one used in `IssueEditActivity`. I made the necessary changes to make sure that the parent milestones list reloads its data if it was the one that opened the edit screen.
> Add shortcuts to enter labels and milestone management screens

- src/com/gh4a/activities/IssueEditActivity.java
- src/com/gh4a/activities/IssueListActivity.java
The refresh code is no longer needed as a list refresh will be automatically executed when the user closes the newly opened activity.
Closes #496 and fixes #458.
> Open issue after creation

- build.gradle
They are not used, yet they block F-Droid builds
> Delete old repositories [F-Droid 1/4]

- app/src/main/java/com/gh4a/BrowseFilter.java
- app/src/main/java/com/gh4a/activities/RepositoryListActivity.java
- app/src/main/java/com/gh4a/fragment/RepositoryListContainerFragment.java
- app/src/main/java/com/gh4a/loader/UserLoader.java
Added link handling for:
- user repositories: https://github.com/Tunous?tab=repositories
- user starred repositories: https://github.com/Tunous?tab=stars
- user followers: https://github.com/Tunous?tab=followers
- user follows: https://github.com/Tunous?tab=following
- organization profile: https://github.com/orgs/twitter
- organization members: https://github.com/orgs/twitter/people
Also fixed `RepositoryListActivity` up arrow - now it navigates to `UserActivity`.
> Handle organization links and user link tab query parameter

- app/src/main/java/com/gh4a/BrowseFilter.java
- app/src/main/java/com/gh4a/activities/DiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/adapter/IssueEventAdapter.java
- app/src/main/java/com/gh4a/fragment/PullRequestFilesFragment.java
- Added support for links to pull request file diff comments,
- Fixed an issue where line highlight was sometimes off,
- Going to file from commit comment in pull request comment list now will highlight that comment
Comments made from pull request changed files tab now work correctly for me. Some examples:
https://github.com/Tunous/TestingRepo/pull/48/files#r118826933
https://github.com/Tunous/TestingRepo/pull/48/files#r118826906
But there is also another type of comments. These which were made on individual commits. They don't appear for me in the app so I didn't add a support for their links in this pull request. Example links:
https://github.com/Tunous/TestingRepo/pull/48/commits/4688cfb2a16ce4f35c70e36c02a672c34ec48a50#r118826927 …
> Pull request diff comment links

- app/src/main/java/com/gh4a/activities/home/NotificationListFactory.java
- app/src/main/java/com/gh4a/fragment/NotificationListFragment.java
- app/src/main/java/com/gh4a/loader/HasNotificationsLoader.java
- app/src/main/java/com/gh4a/loader/NotificationHolder.java
- app/src/main/java/com/gh4a/loader/NotificationListLoader.java
- app/src/main/res/menu/notification_list_menu.xml
- app/src/main/res/values/strings.xml
- github-api/src/main/java/org/eclipse/egit/github/core/service/NotificationService.java
Added as fragment tabs but maybe it is better to use filters in the right drawer. Switching to other tabs would be rare so there is no need to waste data by loading all the tabs when you enter notifications screen just to see unread notifications. Alternatively, maybe there is a way to not load data in other fragments until you switch to them?
> Add loading of all and participating notifications

- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/adapter/CodeSearchAdapter.java
- app/src/main/java/com/gh4a/fragment/SearchFragment.java
- app/src/main/java/com/gh4a/utils/StringUtils.java
- app/src/main/res/layout/row_code_search.xml
- app/src/main/res/layout/row_search_match.xml
- app/src/main/res/values/ids.xml
- github-api/src/main/java/org/eclipse/egit/github/core/TextMatch.java
The appearance of code search results was changed so it's now possible to click on individual matched code blocks. When doing so the opened file will be automatically scrolled to the matched block.
Closes #597.
> Make code search results scroll to matching fragments

- app/src/main/assets/codeutils.js
- app/src/main/java/com/gh4a/activities/CommitDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/DiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/WebViewerActivity.java
- app/src/main/res/layout/popup_menu_item.xml
- app/src/main/res/menu/commit_comment_actions.xml
- app/src/main/res/menu/file_line_menu.xml
- app/src/main/res/values/strings.xml
This is an incomplete change which adds line link sharing _only_ for diffs. It's built on top of the existing popup for comments. I've improved it to use standard Android popup and added Share option to it for this new action. It also works for sharing links to comments.
Similar popup could be implemented for non-diff files. I didn't do it here as it needs some javascript code to make lines clickable and I'm not really sure what's a nice way to do this. Alternatively, for these files only line numbers could be clickable but similarly, I have no ideas how to add that...
#494
> Line link sharing

- app/src/main/java/com/gh4a/activities/IssueListActivity.java
- app/src/main/java/com/gh4a/fragment/RepositoryListContainerFragment.java
The expanded state was restored based on whether the search query was set to `null` or not. This method was not working correctly due to one issue: After collapsing, the search view's `onQueryTextChange` method was called again with an empty string as a parameter value, which in turn resulted in search view getting incorrectly expanded after restoring the state.
The solution was to add another field which tracks whether the search view should be expanded separately from the value of the search query.
Closes #594
> Fix search expanded state being restored incorrectly

- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/res/menu/release.xml
I've decided to set showAsAction to "never" as opening in browser is not a common action and I prefer the more minimal look of the toolbar when it displays only 3-dots icon.
Closes #633
> Add open in browser action to release list and release info screens

- app/src/main/res/menu/repo_list_menu.xml
In my opinion, it's rather awkward that the menu item to open the right drawer is not the rightmost icon. So, I swapped them.
> swap repo menu item position

- app/src/main/res/layout/issue_comment_list_header.xml
- app/src/main/res/layout/issue_create.xml
(And also in issue header)
I've made this change because editing labels is the most commonly performed action from these in the settings screen. (At least from my experience.) Currently, the option to do so is located as the last action
which requires scrolling to reach and is really annoying.
Instead, after this change milestones are positioned as last option because these seem to be the least commonly used action.
> Change order of issue properties in edit screen

- README.md
Right now there's a lot of blank space at the top of the readme. This helps with that.
> Right align icon to save vertical space

- app/build.gradle
- app/src/main/java/com/gh4a/resolver/BrowseFilter.java
- app/src/main/java/com/gh4a/resolver/CommitCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/CommitDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/DiffHighlightId.java
- app/src/main/java/com/gh4a/resolver/DiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/main/java/com/gh4a/resolver/PullRequestDiffCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewLoadTask.java
- app/src/main/java/com/gh4a/resolver/RefPathDisambiguationTask.java
- app/src/main/java/com/gh4a/resolver/ReleaseLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserFollowersLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserReposLoadTask.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
I've moved the parsing algorithm out of BrowseFilter to a separate class
so it was possible to introduce unit tests. There are now 68 tests which
result in 100% test coverage of the new LinkParser.
Only behavior change in the app introduced by this commit is that
"https:github.com" url now opens the main application screen instead of
a browser.
> Refactor link parsing

- app/build.gradle
- app/src/debug/res/values/strings.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gh4a/db/BookmarksProvider.java
- app/src/main/java/com/gh4a/db/SuggestionsProvider.java
This allows installing debug and release builds side-by-side, so you can test WIP changes without uninstalling the current stable version.
When I've done this in the past, there's sometimes places where you'll get unintended dialogs prompting which app you want to complete the action in (for example, when both apps define the same intent filter). These can be fixed as we find them, and also they're acceptable since the people running debug versions know to expect that.
So far I have not done much testing, but I have started using this locally and it seems to work fine. The only duplicate intent filter I found so far is opening `gh4a://` links during github authorization. I don't have time to fix that right now, but I think this is ok to merge even so (or you can do it).
TODO:
> Change applicationId on debug builds

- app/src/main/java/com/gh4a/activities/RepositoryListActivity.java
- app/src/main/java/com/gh4a/activities/home/BookmarkFactory.java
- app/src/main/java/com/gh4a/activities/home/HomeActivity.java
- app/src/main/java/com/gh4a/activities/home/RepositoryFactory.java
- app/src/main/java/com/gh4a/fragment/RepositoryListContainerFragment.java
- app/src/main/java/com/gh4a/fragment/StarredRepositoryListFragment.java
- app/src/main/res/drawable/sort_order.xml
- app/src/main/res/menu/home_nav_drawer.xml
- app/src/main/res/menu/repo_filter_logged_in.xml
- app/src/main/res/menu/repo_starred_list_menu.xml
- app/src/main/res/values/strings.xml
Related to #578, #624 and #725
> Move starred repositories to bookmarks screen

- app/proguard-rules.pro
example: Feed.apply() is currently optimized away by proguard in release build, resulting in blank entries in recent wiki updates list and blank github blog previews (title of blog entry is shown).
We could just add `@org.simpleframework.xml.core.* <methods>` but IMHO replacing with `@org.simpleframework.xml.** *` is more future-proof.
> keep simplexml annotated methods too

- app/src/main/java/com/gh4a/fragment/PullRequestFragment.java
- app/src/main/java/com/gh4a/utils/SingleFactory.java
Stacktrace for NPE:
```
E/AndroidRuntime(729): FATAL EXCEPTION: main
E/AndroidRuntime(729): Process: com.gh4a, PID: 729
E/AndroidRuntime(729): io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
E/AndroidRuntime(729): 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
E/AndroidRuntime(729): 	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onError(ReactiveLoaders.java:51)
E/AndroidRuntime(729): 	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33)
E/AndroidRuntime(729): 	at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
E/AndroidRuntime(729): 	at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109) …
```
> Some fixes

- app/src/main/java/com/gh4a/fragment/RepositoryFragment.java
- app/src/main/java/com/gh4a/fragment/UserFragment.java
- app/src/main/java/com/gh4a/widget/OverviewRow.java
- app/src/main/res/drawable/icon_following.xml
- app/src/main/res/drawable/icon_private.xml
- app/src/main/res/layout/repository.xml
- app/src/main/res/layout/user.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
Few changes and fixes to the repository information screen. Main differences are:
- Moved information telling that the repository is private to appear like other rows.
- Moved information about fork parent to also appear like other rows. I'm not sure about this change since now the icon is the same as for forks count row but I also didn't like how it looked like previously. Perhaps there is some other better looking way to display this information?
- Removed information about repository url if no custom homepage was set. This is a bit controversial change but I think it is useless to display default url when it's posible to get that link through share/open in browser actions.
> Repository ui polish

- app/build.gradle
This allows us to bump the compileSdk to 28.
https://bigbadaboom.github.io/androidsvg/release_notes.html
> Bump androidsvg-aar from 1.3 to 1.4

- app/src/main/java/com/gh4a/fragment/SettingsFragment.java
- app/src/main/res/layout/about_dialog.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
First of all thank you for your great app.
As the title says, this adds a link to the source code in the about dialog and removes the space between the left side and the settings.
Personally, I like a direct link to the source code more, than first being redirected to the issues and then going back to the source code.
> Add source code link in about & move settings to the left

- app/src/main/AndroidManifest.xml
Fixes #1091 by adding a `<queries>` tag to manifest file [as recommended by Android docs](https://developer.android.com/training/package-visibility/use-cases#open-urls).
> Fix inability to find installed browser on Android 11

- app/src/main/java/com/gh4a/adapter/timeline/ReviewViewHolder.java
Apparently, in this specific case GitHub API returns a null user instead of "ghost" as it usually does.
Fixes #1082
> Fix crash when a PR review is made by a deleted user

- app/src/main/res/drawable-night/private_small.xml
- app/src/main/res/drawable/private_small.xml
It arguably looked wrong.
Before:
After:
> Fix size of private repo/gist icon in list

- app/src/main/java/com/gh4a/fragment/IssueListFragment.java
They didn't work due to a typo.
> Fix Most/least commented sort options

- app/src/main/java/com/gh4a/model/StatusWrapper.java
Currently, the app crashes when opening PR PowerShell/PowerShell#9115 due to a completed check run (the one called "WIP") that weirdly has a null `completionAt` field.
This PR handles this edge case by avoiding to print the check run execution time, as the GitHub UI does.
> Fix crash when start/completion dates are null in completed check runs

- app/src/main/AndroidManifest.xml
This PR adds to the manifest the needed `meta-data` tag to opt this app out from WebView usage statistics collection.
Fixes #1061
> Opt-out from WebView usage statistics collection

- app/src/main/AndroidManifest.xml
I've noticed just now that Crashlytics was removed in a previous version, this seems to be the last leftover remained.
> Remove leftover Crashlytics API key

- app/src/main/java/com/gh4a/ServiceFactory.java
- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
- app/src/main/java/com/gh4a/fragment/IssueFragment.java
- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/fragment/PullRequestFragment.java
- app/src/main/java/com/gh4a/utils/RxUtils.java
While I was investigating why loading a PRs with lots of comments was extremely slow, I opened up the Android Studio network profiler and saw this:
What was happening in thread RxNewThreadScheduler-23 was that these API calls used to load the PR conversation:
https://github.com/slapperwan/gh4a/blob/dfdf3e1d46a4c9c3fcfa5dac3d3df5bec1350d3b/app/src/main/java/com/gh4a/fragment/PullRequestFragment.java#L315-L320
were all being executed sequentially!
To execute them in parallel, I only needed to explicitly subscribe each of those `Single`s on a background thread (63d4032).
After this change, this is what I saw in the profiler:
Much better. The conversation of that specific PR (PowerShell/PowerShell#9900) now takes half the time to load (from 20 to 10 secs).
I noticed that also issues had the …
> Improve PRs/issues loading performance

- app/src/main/res/values/themes.xml
This PR fixes the app theme so that the accent color is applied consistently to both text links and headers/icons.
This greatly improves legibility of green text and green icons' contrast when using the dark theme.
Fixes #1079
> Fix poor green text/icon contrast on dark theme

- app/build.gradle
- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/widget/StyleableTextView.java
- app/src/main/res/layout/release.xml
In this PR I tried to use the newly added Release's bodyHtml field to avoid calling the Markdown API to format the Release body.
However, it seems that HttpImageGetter doesn't behave properly. Here's what I see as soon as I open a release:
The TextView has a gray background (instead of white) and the view is already scrolled down to the release body.
Am I doing anything wrong?
> Avoid an unnecessary API call to load formatted Release body

- app/src/main/java/com/gh4a/activities/DiffViewerActivity.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
This PR fixes a crash that was occurring when tapping on a file (in PR Files tab) to open the diff in PR PowerShell/PowerShell#9900, caused by a TransactionTooLargeException due to lots of big review comments.
Here I've used the same approach that has been used for the CommitFragment (gzipping the data into the bundle), though I had to write new methods for this specific context. After fixing the issue, I did my best to remove the duplication I had introduced.
> Fix TransactionTooLargeException when opening a diff with lots of comments

- app/src/main/res/layout/row_suggestion.xml
This PR makes a couple of small changes to make the search suggestion experience more comfortable:
- start the search directly when a suggestion is clicked
- make suggestion text a little bit smaller and ellipsize text in the middle when it's too long. This greatly improves the UX when searching code.
Below you can see the same example before and after this change:
> Improve search suggestions ergonomics - round 1

- app/src/main/java/com/gh4a/adapter/CommitAdapter.java
~~This PR gets rid of PrettyTime to format relative dates and instead uses the built-in Android `DateUtils` class, so that the actual date is displayed when it is more than one week in the past.~~
~~Another difference is that `DateUtils` displays _"Yesterday"_ instead of _"1 day ago"_ (doesn't it sound a bit weird?).~~
~~Another small tweak I made was to change the commit list to display the actual commit dates instead of the authoring dates.~~
~~In this way some commits don't feel "out of place", as you can see the in the screenshots below comparing that list before and after this PR (the user can still see the authoring date in the commit details activity).~~
> Show dates for commits older than 1 week in commit list

- app/src/main/java/com/gh4a/resolver/CommitCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/CommitDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/DiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/main/java/com/gh4a/resolver/PullRequestDiffCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/PullRequestReviewLoadTask.java
- app/src/main/java/com/gh4a/resolver/RefPathDisambiguationTask.java
- app/src/main/java/com/gh4a/resolver/ReleaseLoadTask.java
- app/src/main/java/com/gh4a/resolver/UrlLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserFollowersLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserLoadTask.java
- app/src/main/java/com/gh4a/resolver/UserReposLoadTask.java
- app/src/main/java/com/gh4a/widget/LinkSpan.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
This PR fixes a couple of regressions introduced by #1118:
- many non-GitHub links erroneously resolved to OctoDroid activities, because the LinkParser didn't take into account the possibility of receiving non-GitHub URLs
- tapping on links to relative URLs (such as anchor links in Readme) made the app crash due to an NPE
- when an URL couldn't be resolved to an OctoDroid activity, it wasn't opened in the browser as it should have been
Also, tests didn't compile until I fixed them. Ideally there should be a pipeline that builds the app and runs them, so that at least they have a chance to run from time to time :)
> Fixes for link handling regressions

- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
- app/src/main/res/layout/pull_merge_message_dialog.xml
- app/src/main/res/values/strings.xml
This PR adds the ability to customize the merge commit title, which previously was always generated by GitHub.
When the user doesn't enter a title, GitHub still provides its auto-generated title. To make this clear to the user, I have added a hint to the title EditText containing the title that GitHub will generate if the user doesn't type in anything. Here's an example:
While implementing this, I've done some refactoring to the MergeDialogFragment otherwise things would have become a bit too messy :smiley:
> Allow changing commit title when merging a PR

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
This PR improves the conversions of HTML tables to spans, so that the text gets at least laid out in a readable fashion instead of appearing as a garbled mess.
This basic improvement then allowed me to greatly improve the rendering of suggested changes snippets in reviews and embedded code snippets in comments, since they were rendered as HTML tables by GitHub.
In the last commit I've decluttered the HtmlToSpannedConverter a bit by converting some static methods to instance methods to avoid passing the spannable string builder around all the time. This has been done entirely with automated refactorings by Android Studio, so there shouldn't be any risk of regressions.
Here are some comparisons:
<table>
<tr><td>
</td><td><img …
> Improve tables and embedded code snippets/suggested changes rendering

- app/build.gradle
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/LoadingFragmentBase.java
- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/widget/CommitStatusBox.java
- app/src/main/java/com/gh4a/widget/OverviewRow.java
- app/src/main/res/layout/commit_status_box.xml
- app/src/main/res/layout/loading_fragment.xml
- app/src/main/res/layout/overview_row.xml
- app/src/main/res/values/strings.xml
This PR mitigates the sometimes very slow loading of issue/PR conversations (due to GH REST API limitations we all know) by showing the issue/PR body as soon as possible, instead of waiting for the rest of the conversation to load.
This can be best demonstrated by the screencast here: https://streamable.com/aj4p28.
This way, the user can start reading the content of the issue/PR without waiting, drastically reducing the perception of the loading times.
The only thing I'm not too sure about is whether we should keep the editor bottom sheet hidden while loading is in progress. There is technically nothing that can prevent us not to show it, but at the same time it doesn't make much sense to use it before the conversation is loaded.
**Note:** I've tried to workaround some issues with the …
> Make issue/PR body visible while the rest of the conversation is still loading

- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/main/java/com/gh4a/resolver/RefPathDisambiguationTask.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
This PR adds handling for special GitHub URL segments that the app previously treated mistakenly as GH users (such as /issues, /notifications, /timeline etc.).
The list of GitHub reserved names was also greatly expanded with page names of their website (all added pages have been manually checked).
I've also made a performance tweak to the RefPathDisambiguationTask, so that it doesn't unnecessarily try to resolve the ref to a branch/tag name when the ref is a SHA1. I don't think anyone sane would name a branch like `<full SHA1>/something` :sweat_smile:
> URL resolution improvements

- app/src/main/java/com/gh4a/adapter/timeline/DiffViewHolder.java
- app/src/main/res/layout/commit_filename.xml
This small PR changes inline diff hunks in reviews to make line numbers use a monospaced font, so that the start of the line of code is now perfectly aligned, as you can see from the screenshots below.
<table>
<tr><td>
</td><td><img src="https://user-images.githubusercontent.com/30041551/141442086-c5c5c181-6f97-43b8-bbc4-3f22634926d8.png" /></td></tr>
</table>
I didn't use monospace for all the code in the diff hunk for compactness reasons: when code is moderately indented (20+ spaces), you would always need to scroll right to be able to read the text.
While making this change, I've noticed that the diff was originally intended to have a monospace font, but there is a bug in `StyleableTextView` that causes the attribute `android:typeface` to be …
> Make line numbers monospaced in review inline diffs

- app/src/main/java/com/gh4a/BaseActivity.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/LoadingFragmentBase.java
- app/src/main/java/com/gh4a/utils/UiUtils.java
Small improvement on top of #1128.
This PR aims to avoid rapid pop-in of items when issue/PR conversations have none to few comments and therefore load very fast.
The issue/PR body will get displayed after 800ms if the entire conversation hasn't been loaded yet. For conversations that load faster than 800ms, the app will behave the same as it did before #1128 (show the content as soon as everything is loaded).
> Avoid pop-in when issue/PR conversation loads fast enough

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
- app/src/main/res/values/strings.xml
This PR adds a small QoL life change to allow viewing embedded videos in comments in the app.
Before this PR, you had to open the comment in the GitHub website in order to see an embedded video, because the app displayed only the name of the video file.
Now, a "View video" link will appear near the video name, which opens the video in a custom tab, as you can see in the screenshot below:
I initially thought of making the video file name a clickable link, but it turned out to be too difficult since the `<video>` tag is after the name (which is a `<span>`) in the HTML.
> Add basic support for embedded videos in comments

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/activities/GistViewerActivity.java
- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/activities/RepositoryActivity.java
- app/src/main/java/com/gh4a/fragment/ContentListFragment.java
- app/src/main/java/com/gh4a/fragment/EventListFragment.java
- app/src/main/java/com/gh4a/utils/DownloadUtils.java
- app/src/main/java/com/gh4a/utils/HttpImageGetter.java
- app/src/main/java/com/gh4a/utils/UiUtils.java
This PR adds a required permission to the manifest so that downloaded APKs can be installed directly by tapping on the download notification on Android 6+.
I've also extracted download-related methods that were in `UiUtils` in a separate `DownloadUtils` class (I felt they were out of place while looking at the code) ~~and renamed the receiver responsibile for intercepting clicks on pending download notifications~~.
Fixes #1067
> Allow direct installation of downloaded APKs

- app/src/main/java/com/gh4a/BaseActivity.java
- app/src/main/java/com/gh4a/activities/IssueActivity.java
- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
- app/src/main/java/com/gh4a/fragment/IssueListFragment.java
- app/src/main/res/layout/error.xml
- app/src/main/res/values/strings.xml
We will never get rid of them (as long as we use the current bindings library). GH can always add new enum values to enums that don't have a null fallback, or there may be enum bindings that are not exhaustive.
Now these errors have a specific error message, so that the user knows what's going on.
Also, I thought it would be a good idea to log all handled exceptions as errors in logcat to make them more prominent.
> Do not crash the app on Moshi's JsonDataExceptions

- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/fragment/RepositoryListContainerFragment.java
- app/src/main/res/layout/main.xml
- app/src/main/res/layout/repository.xml
- app/src/main/res/layout/row_timeline_review.xml
- fix links not being clickable on links in pull request reviews (`needsLinkHandling` attribute was missing on the TextView)
- replace last usages of deprecated `onActivityCreated` method with `onViewCreated`
- apply MD2 styling to the "Login" button
- make URLs in repository description clickable (see for example https://github.com/standardnotes/desktop)
> A couple of smallish fixes/tweaks

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/com/gh4a/Gh4Application.java
- app/src/main/java/com/gh4a/ServiceFactory.java
- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- app/src/main/java/com/gh4a/fragment/CommitFragment.java
- app/src/main/java/com/gh4a/fragment/ContentListContainerFragment.java
- app/src/main/java/com/gh4a/model/StatusWrapper.java
This PR updates bindings to version 0.7.0.7 and includes the following improvements:
- JodaTime has been removed (debug builds of the app are almost 1MB smaller)
- the new `getContentsRaw` method has been used to retrieve text file contents in some cases (issue templates, gitmodules)
- `waiting` state for check runs is now handled (fixes #1169)
- commit details now display the previous filename for deleted files.
The best and simplest solution I came up with is the one you can see in the screenshots below (the previous filename is ruled-out).
I also tried to do something like "OLD FILENAME → NEW FILENAME", but the `→` symbol looks terrible in Roboto.
I'm open to any suggestions for improvement.
Last but not least, the default header for all API requests has been changed so that API …
> Update bindings and leverage new features

- app/src/main/java/com/gh4a/activities/WikiActivity.java
- app/src/main/java/com/gh4a/model/Feed.java
- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
This PR fixes two bugs related to repository wikis:
- links to specific wiki pages incorrectly resolved to the "Recent Wiki Updates" screen (#1127).
Those links now open the wiki page in a browser, since GH doesn't have an API for fetching a wiki page content in order to display it in a WikiActivity.
- app crashed when opening some very large wiki pages from the "Recent Wiki Updates" screen (e.g. https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0) due to a TransactionTooLargeException (page content is passed via intent extras).
To fix this, I've made `Feed` implement `Parcelable` and passed it as a whole to the WikiActivity, compressing it as needed. At first I tried to compress/decompress just the `content` intent extra, but I didn't manage to: Android has no public APIs to …
> Fix a couple of wiki-related bugs

- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/fragment/ReviewFragment.java
- app/src/main/java/com/gh4a/model/TimelineItem.java
In order to load the PR conversation, the app fetches also all the files that have been changed in the PR.
The data related to changed files is used only by the _"View in file"_ menu action, which is available only for review comments that are not outdated. Since those comments are displayed in the review details screen and **not** in the conversation (except in one case, explained below), fetching that data is unnecessary in order to load the conversation.
This optimization greatly speeds up conversation loading for PRs which have lots of changed files, such as k0shk0sh/FastHub#2599. Another extreme example is topjohnwu/Magisk#5134 which has something like 5000 changed files which take **minutes** to be fetched.
There is only one thing that we lose by not fetching changed files anymore: …
> Avoid fetching changed file in order to load PR conversations

- app/src/main/java/com/gh4a/model/GitHubFeedService.java
A few days ago GitHub silently changed the URL of the atom feed of their blog.
This PR updates the URL in the app so that the feed can be retrieved correctly.
> Update GitHub blog feed URL

- app/src/main/res/layout/row_commit.xml
- app/src/main/res/layout/row_event.xml
- app/src/main/res/layout/row_issue.xml
This PR makes some lists look better (commits, issues and activity lists) when usernames are too long to fit in one line.
The layouts have been adjusted (using [this trick](https://stackoverflow.com/a/48199856)) to make sure that the timestamp of the item never gets shrunk/wrapped and the username gets ellipsized or wrapped if it's too long.
Here are some before/after comparisons:
<table>
<tr><td>
</td><td>
<tr><td>
</td><td>
<tr><td>
</td><td>
</table>
Implementation notes: in some places I have added `tools:ignore="InefficientWeight"` because Android Studio suggests to set the width to 0dp to improve rendering performance, but it causes TextView sizes to be messed up after scrolling the RecyclerView.
> Improve lists UI behaviour when there are long usernames

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
I've noticed that lines of code inside code snippets in comments didn't have any indentation because they weren't considered as preformatted text.
> Fix indentation in code snippets

- app/src/main/java/com/gh4a/adapter/timeline/EventViewHolder.java
- app/src/main/res/values/strings.xml
This PR makes the following improvements to the way `referenced` and `cross-referenced` timeline events are displayed:
- `referenced`: display also repository owner and name together with the SHA of the commit that referenced the issue/PR, if it belongs to another repository.
I've also reworded the message for the event since I've discovered that references from commit comments (and not only from commit messages) appear as `referenced` events too (see [this](https://github.com/PowerShell/PowerShell/pull/16840#ref-commit-f8168cb) for an example), and therefore the message _"added commit [] that referenced this issue"_ could have been misleading.
- `cross-referenced`: display also repository owner and name together with the number of the issue that referenced the issue/PR, if it belongs to …
> Improve clarity for `referenced` and `cross-referenced` timeline events

- app/src/main/java/com/gh4a/utils/FileUtils.java
This PR includes the following fixes:
- .mjs files (ES Modules) won't be recognized as binary files anymore on Android 11+ (#1177) and will therefore be opened in the in-app code viewer
- when querying the MIME type overrides map, we were assuming that the extension was always lowercased, and therefore a `.bat` file would have been opened in-app whereas a `.BAT` file would have been opened in the browser.
We now always use the lowercased extension to avoid this issue.
Fixes #1177
> A couple of small MIME type detection fixes

- app/build.gradle
- app/src/main/java/com/gh4a/fragment/ReleaseListFragment.java
I've noticed that the sorting issue of the Releases API we worked around in #1112 has been fixed on GitHub side.
I asked to GH support for confirmation and they told me that "the fix was rolled out late last month". :tada: 
Therefore this PR removes the workaround since it's not needed anymore.
> Remove workaround for releases API sorting misbehavior

- app/src/main/java/com/gh4a/fragment/CommitFragment.java
Previously, added/removed lines weren't shown when the GitHub API didn't return the full diff of a file (most often because it was too big).
Additions/deletions are always returned by the API, even for non-text files (in those cases they will be both set to 0).
> Show file stats (additions/deletions) when full diff is not available

- app/src/main/java/com/gh4a/activities/IssueActivity.java
This PR fixes #1172 by reusing the IssueFragment that gets automatically restored after rotation, instead of creating a new fragment and "injecting" the saved state of the previous one into it.
> Avoid refetching issue conversation on screen rotation

- app/src/main/java/com/gh4a/utils/FileUtils.java
- app/src/main/java/com/gh4a/utils/HttpImageGetter.java
While I was taking a look at how the app fetches images in comments and Readmes, I was surprised to discover that before rendering, images were being written to a temporary file just to be read from it immediately after.
Among a couple of small refactorings, the PR changes the logic to avoid this unnecessary and inefficient step, which also spares us quite a bit of boilerplate error handling code.
> Optimize image loading by avoiding redundant file read/writes

- app/src/main/java/com/gh4a/model/GitHubFeedService.java
Apparently GitHub changed their mind and brought back the old URL :)
Reverts #1176
> Revert "Update GitHub blog feed URL"

- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
I've discovered by chance that the app handles links to release assets (e.g. https://github.com/slapperwan/gh4a/releases/download/4.6.7/gh4a-467-release.apk) incorrectly, causing a redirect to the Releases list screen.
I've changed the behavior so that those links don't get handled and the browser is opened instead, so that the user can download the file.
> Fix incorrect handling of release assets links

- app/src/main/java/com/gh4a/activities/RepositoryListActivity.java
- app/src/main/java/com/gh4a/fragment/RepositoryListContainerFragment.java
- app/src/main/res/menu/repo_filter_org.xml
I've found and fixed a few bugs in the user repositories list screen, specifically:
- b56fdd4 accidentally broke the ability to list starred repositories of other users (the "Starred" filter did nothing)
- several repository list filters weren't working for organizations, because either didn't make sense (Starred, Watched, Member) or aren't supported by [the API endpoint we're using](https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user) (Public, Private). Those broken filters have been removed.
- available sorting options in the right navigation drawer weren't correctly refreshed when selecting the "Watched" or "Starred" filter. This bug affected only the repositories list screen of other users (not the "My repositories" screen of the home activity).
> A few fixes to the repositories list

- app/src/main/assets/markdown-dark.css
- app/src/main/assets/markdown-light.css
- app/src/main/assets/markdown-print.css
- app/src/main/assets/mdpreview-dark.css
- app/src/main/assets/mdpreview-light.css
- app/src/main/assets/prettify-dark.css
- app/src/main/assets/prettify-light.css
- app/src/main/assets/text-dark.css
- app/src/main/assets/text-light.css
- app/src/main/assets/text-print.css
- app/src/main/java/com/gh4a/activities/BlogActivity.java
- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/activities/WebViewerActivity.java
- app/src/main/java/com/gh4a/activities/WikiActivity.java
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
This PR makes more improvements to WebView styles, with a few more fixes and tweaks:
- fix printing of Markdown previews, which was not working anymore after leveraging `JavascriptInterface`s more extensively
- change background color of WebViews to be exactly the same as the app UI, by setting it to transparent.
Previously it was set to a slightly different shade of grey compared to the other screens.
- improve CSS styles, particularly spacing and text contrast in dark theme as you can see below:
<table>
<tr><td>
</td><td>
</table>
- markdown CSS styling is now also applied to wiki pages and GH blog posts. It makes them look considerably better, as images do not overflow the page anymore:
<table>
<tr><td> …
> Further improve WebView styling

- app/src/main/java/com/gh4a/adapter/FileAdapter.java
- app/src/main/java/com/gh4a/fragment/ContentListContainerFragment.java
- app/src/main/java/com/gh4a/fragment/ContentListFragment.java
This PR makes a couple of small adjustments to the available context menu entries for submodules in files list:
- "Download" entry does not work (and doesn't make much sense for a submodule) and thus has been removed
- "History" entry was previously hidden for submodules, but I've discovered that works as intended and can be useful to see all commits in which a submodule has been updated
I've also made an extra commit to get rid of a few null checks by returning an empty collection instead of null.
> Show "History" but not "Download" context menu entries for submodules

- README.md
- metadata/en-US/short_description.txt
I've made the F-Droid _short_description_ of the app more concise, as it is currently getting truncated on the [website](https://f-droid.org/packages/com.gh4a/).
Also, I've found out that build instructions in Readme referenced a specific SDK and build-tools version. I've decided to remove the version since it will keep changing in the future anyway, and it's too easy to forget to keep the Readme in sync.
> Shorten F-Droid short description + Readme fix

- app/src/main/java/com/gh4a/fragment/NotificationListFragment.java
74e01129 introduced a regression that caused notifications not being marked as read after opening them in most cases:
https://github.com/slapperwan/gh4a/blob/74e01129f3f1df50451afaf28808dbacc1cd84e8/app/src/main/java/com/gh4a/fragment/NotificationListFragment.java#L143-L146
When the above `if` condition is true, the notification is not marked as read.
This PR proposes a simpler fix for #1208 since the problem with "unsupported" notifications (like discussion ones) is that they don't have a URL, because if they had it, the URL would be opened in a browser/custom tab instead of doing nothing.
I've tested this fix with a PR notification and a discussion notification and it behaved as expected.
> Fix regression when marking notifications as read

- app/src/main/java/com/gh4a/activities/IssueActivity.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
- app/src/main/java/com/gh4a/widget/LinkSpan.java
- app/src/main/java/com/gh4a/widget/MarkdownPreviewWebView.java
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
This PR fixes the following small regressions:
- issue conversation wasn't being refreshed anymore after editing the issue, introduced by #1193 
- #1114 accidentally made the accent color slightly darker for light theme, causing icons and some headings to have a darker tone of green
The PR also extends the improved link-handling logic introduced in #1118 to Markdown previews (724cf56 was needed for it to work in the comment editor) and disabled WebView filesystem access for them as we did in #1180.
> A couple of regression fixes and link handling improvements

- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/activities/RepositoryActivity.java
- app/src/main/res/layout/error.xml
This PR fixes #886 by skipping the cache for the API call that retrieves the repository details.
I've also added a few more fixes:
- when opening a renamed/moved repository from a link with the older name (e.g. https://github.com/k9mail/k-9), the repo name in the title bar will be updated with the actual repository name instead of displaying the older name
- added a missing `needsLinkHandling` attribute that made impossible to open links found in the loading error message (an example of an error message containing links is the DMCA takedown notice)
- swipe-to-refresh in the Release details screen has been disabled in all cases in which it did nothing (that is, when the release was passed via intent extras)
> Fix a few smallish bugs

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
I've made a couple of adjustments regarding text sizes to Markdown rendering in comments/Readme:
- <sub>subscript</sub>/<sup>superscript</sup> text is now smaller, to make it look as it does in GitHub web UI
- sizes of H1 to H6 has been changed to make the different types of heading more clearly distinguishable. Previously I had a hard time finding the difference between an H1 and an H2, or between an H2 and an H3. You can see below the difference:
<table>
<tr><td>
</td><td>
</table>
> Improve text sizes in Markdown rendering

- app/src/main/java/com/gh4a/model/Feed.java
- app/src/main/java/com/gh4a/utils/HtmlUtils.java
This PR includes some changes to the HTML-to-spanned-text converter that fix some formatting inconsistencies between the app and the GitHub UI:
- `<pre>` tags are now treated as code blocks (as the GitHub UI does) instead of being rendered as monospaced pre-formatted blocks without a background.
This change also allows to simplify the handling of highlighted code blocks: they don't need to be handled in a special way since they are just `pre`s wrapped in a `div`.
- `<tt>` tags are now treated in the same way as `<code>` tags
- `<samp>` tags are now rendered as simple monospaced inline text (they were previously ignored)
- rendering of numbered lists was improved: nested `<ol>s` and ordered lists which have newlines between each item are now displayed correctly.
This was done by …
> HTML conversion fixes and small improvements

- app/src/main/java/com/gh4a/adapter/timeline/EventViewHolder.java
- app/src/main/res/drawable-night/issue_event_closed_completed.xml
- app/src/main/res/drawable/issue_event_closed_completed.xml
- app/src/main/res/values/strings.xml
This PR keeps OctoDroid up with the [changes GitHub has recently made to the "closed" issue status](https://github.com/github/roadmap/issues/289):
- the "closed as completed" and "closed as not planned" information has been added to the `closed` timeline event
- ~~the IssueActivity/Fragment color has been changed to purple if the issue is _closed as completed_.~~
~~For _closed as not planned_ issues I've kept the classic red color - even if GitHub UI uses dark grey - for consistency with the closed red icon that is already used in the app, and because the grey color used by GH is very similar to the grey used for PR draft status (and draft issues may be a thing in the future, according to the issue linked above)~~
- ~~the Closed tab in the Issues list has had its color changed from red to …
> Display issue closed reason in timeline events

- app/build.gradle
- app/src/main/java/com/gh4a/adapter/SearchAdapter.java
- app/src/main/java/com/gh4a/fragment/BookmarkListFragment.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/NotificationListFragment.java
- app/src/main/java/com/gh4a/utils/HttpImageGetter.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
- app/src/main/res/drawable-night/image_error.xml
- app/src/main/res/drawable-night/image_gif_placeholder.xml
- app/src/main/res/drawable/image_error.xml
- app/src/main/res/drawable/image_gif_placeholder.xml
- app/src/main/res/layout/row_search_match.xml
- app/src/main/res/layout/row_timeline_event.xml
This PR is centered around small improvements to the user experience and minor usability fixes:
- placeholder icons for images that aren't loaded in comments/READMEs have been changed: now they differ when an image can't be loaded or when a GIF is not loaded because of the loading preferences (previously the same placeholder was used)
<table>
<tr><td>
</td><td>
</table>
- in code search results, the full path to the matching file is shown instead of just the file name
- the scaling logic for images in comments/READMEs has been adjusted, so that images that are taller than the screen height are not uselessly resized when they aren't wider than the screen (the diagram in [TeamNewPipe/NewPipe#7673](https://github.com/TeamNewPipe/NewPipe/issues/7673) is …
> Miscellanous quality-of-life changes

- app/src/main/java/com/gh4a/model/Feed.java
- app/src/main/java/com/gh4a/utils/StringUtils.java
This is a small fix for a few titles in the GitHub blog feed which contain some unescaped HTML entities.
I've extracted the logic for unescaping the entities in the `StringUtils` class so that it can be reused in other places, if needed.
> Fix some unescaped HTML entities in GitHub blog titles

- app/src/main/java/com/gh4a/fragment/NotificationListFragment.java
- app/src/main/res/values/strings.xml
This small PR puts together a few fixes for some minor bugs I found in the Notifications screen:
- tapping on the repository name accidentally marks all notifications as read (#1255)
- unsubscribing from a notification thread marks the notification as read in the UI, however this isn't done on the server side: after refreshing the screen the notification is still displayed as unread (#1258). 
To address this, I've decided to display a toast to let the user know that the unsubscription was successful, without marking the notification as read.
- if a notification has already been read, avoid calling the API to mark it as read again when the user taps on it.
This prevents useless API calls and works around a weird side-effect (maybe a bug?) of the GH API endpoint, which marks a notification …
> A few fixes to the notification screen

- app/src/main/java/com/gh4a/ServiceFactory.java
This allows to have a much higher rate limit (5000 vs 60 requests per hour) when the user is not logged in, [as described here](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#increasing-the-unauthenticated-rate-limit-for-oauth-apps).
Fixes #717
> Authenticate API calls with OAuth clientId/clientSecret when user is not logged in

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
This PR fixes the crash reported in #1253.
It was a regression introduced by #1239 that highlighted a bug that existed in the HTML-to-spanned conversion before that PR: `<pre>` tags weren't treated as block elements, and therefore they weren't always guaranteed to start on a new line (which is incorrect and was the cause of the crash).
While I was at it, I've noticed that `<details>`/`<summary>` tags weren't handled at all in the HTML conversion. This lead to missing linebreaks which could make the text quite messy like in the following example:
Which results from the following HTML:
```html
<details>
Details without summary
</details>
<details>
<summary>
Custom summary
</summary>
Hello, world!
</details>inline text after details
<summary>
Summary tag outside details
</summary>
more text …
```
> Fix an HTML conversion crash and improve rendering of <details> elements

- app/src/main/res/drawable-anydpi-v26/launcher_bg.xml
- app/src/main/res/values/colors.xml
Before the launcher icon background was brighter when the device was in day mode when the icon has been added. It didn't follow the DayNight mode, so it felt wrong to me to respect DayNight mode.
> Make launcher icon independent from DayNight mode

- app/src/main/java/com/gh4a/activities/PullRequestActivity.java
- app/src/main/java/com/gh4a/adapter/timeline/CommentViewHolder.java
- app/src/main/java/com/gh4a/adapter/timeline/DiffViewHolder.java
- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/model/TimelineItem.java
- app/src/main/java/com/gh4a/utils/FileUtils.java
- app/src/main/res/layout/pull_merge_message_dialog.xml
- app/src/main/res/values/strings.xml
This PR batches together a few bug fixes, mostly regarding PRs (it's easier to review commit by commit):
- avoid showing the "View in file" action in review comments and diff fragments if the entire patch for that file wasn't returned by GH API (e.g. when the diff is too big). Previously, when tapping on "View in file" in these cases, the code viewer would open with a blank screen.
- completely hide (not just disable) Merge and Reopen actions in the app bar when a PR is already merged, since those actions are not possible in that context.
Also, the condition used to determine PR mergeability has been fixed: the Merge action will now be disabled when a PR can't be merged due to conflicts or missing approval.
- the app now shows the error snackbar when the deletion of a pull request branch …
> Fix a few PR-related bugs

- app/src/main/java/com/gh4a/activities/IssueListActivity.java
- app/src/main/java/com/gh4a/fragment/SingleChoiceDialogFragment.java
- app/src/main/res/layout/base_activity.xml
- app/src/main/res/menu/issue_list_filter.xml
- app/src/main/res/menu/issue_list_filter_collab.xml
- app/src/main/res/values/strings.xml
The primary goal of this PR is to allow searching by text and filtering by milestone/label etc. at the same time in issue/PR lists.
Previously, searching for issues by text would silently ignore the filters applied by the user, which was IMHO a confusing and unnecessarily restrictive behavior.
While implementing this, I've also discovered and fixed some issues:
- in the right drawer, the currently selected milestone/label/etc. wasn't being displayed because menu items' text was truncated to 1 line by default
| Before fix | After fix |
|--------|--------|
| ![Screenshot_filter_before](https://user-images.githubusercontent.com/30041551/230727770-20b89787-5e33-40c3-873b-e923c95d1070.png) | ![Screenshot_filter_after](https://user-images.githubusercontent.com/30041551/230727756-35a19a0d-8519-49 …
> Improvements and fixes to issue/PR list filtering

- app/src/main/java/com/gh4a/BaseActivity.java
- app/src/main/res/layout/drawer_header_left.xml
Use dynamic status bar height in the left drawer header instead of the 24dp hard coded
Before / After
> Use dynamic status bar height in the left drawer header

- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/adapter/SearchAdapter.java
- app/src/main/java/com/gh4a/utils/SingleFactory.java
This PR includes some fixes for a few crashes that I have encountered myself or that others have reported:
- #1312: this is caused by incorrect results returned by GitHub code search API. I have already reported the bug to them several months ago, but it still hasn't been fixed on their side. I have added a simple workaround to ignore incorrect match data returned by the API.
- 64b8e550f: this crash could be reproduced by opening https://github.com/rails/rails/releases/tag/v7.1.0, which features an incredibly long changelog
- 3dda7ce5: this is an attempt to fix #1326, which I'm not able to reproduce on my side. It looks like it crashes due to a null `updated_at` field of a notification (which shouldn't even occur according to [their response …
> Fix a few crashes

- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
[Since May 2022](https://github.blog/changelog/2022-05-03-increased-file-size-limit-when-retrieving-file-contents-via-rest-api/), the [repository file contents API](https://docs.github.com/en/rest/repos/contents) does not return an error anymore when fetching files bigger than 1MB.
However, file contents are not included in the JSON payload in those cases, and therefore this makes the in-app file viewer display a blank screen instead of opening the file in the browser as it did previously.
With this PR, the app handles those API responses properly.
> Properly handle API responses for big file contents

- app/src/main/AndroidManifest.xml
Since we no longer target the Play Store, we can re-add the permission that allows downloaded APKs to be installed by tapping directly on the download notification. This was initially introduced in #1130 and reverted in f6f325e.
> Re-introduce ability to install downloaded APKs directly

- app/build.gradle
- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
Just a small PR to fix an issue in organization links handling that I've accidentally discovered thanks to the link in [this comment](https://github.com/slapperwan/gh4a/issues/1336#issuecomment-2212551262).
Before this change, links pointing to an organization subpage (e.g. Discussions, Packages, Settings) confusingly redirected the user to the organization details screen. Now all subpages are opened in the browser, with the exception of _Members_ and _Repositories_ which open the relevant app screens.
I've also updated Robolectric, since the old version was causing unit tests to blow up with a `NoClassDefFoundError` (I guess updating SDK/dependencies broke something).
> Fix handling of some organization links

- app/src/main/java/com/gh4a/adapter/timeline/CommentViewHolder.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/widget/ReactionBar.java
- app/src/main/res/layout/reaction_bar.xml
- app/src/main/res/layout/row_trend.xml
This PR addresses two layout bugs that can occur on devices with small screens:
- the first is the trending repository details row overflowing the screen, as seen in the following screenshot:
- the other one is #1284.
While I was at it, I've also fixed #1283 by hiding "Add reaction" menu items and the corresponding button in the reaction bar when the user is not logged in.
Closes #1284 
Closes #1283
> Fix a couple of layout overflow issues + reaction fixes

- app/build.gradle
- app/src/main/java/com/gh4a/activities/IssueActivity.java
- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- app/src/main/java/com/gh4a/adapter/ItemsWithDescriptionAdapter.java
- app/src/main/res/layout/row_item_with_description.xml
- app/src/main/res/values/strings.xml
This PR implements the ability to specify a reason (_completed_ or _not planned_) when closing an issue by tapping the "Close" action in the app bar.
In #1223 I initially thought that this couldn't be done with the REST API, but luckily I was wrong.
I intentionally kept the close reason descriptions short (almost the same as the GH web UI) so that they fit on a single line even on smaller screens. 
One minor feature that this PR lacks compared to the GH web UI is the ability to change the close reason of an issue without first reopening it. I didn't bother to add it, since I think it will rarely be useful in practice.
In case we really want to have it, we could simply add a "Close as not planned"/"Close as completed" action in the dropdown menu when the issue has already been closed.
> Add ability to select a reason when closing an issue

- app/src/main/java/com/gh4a/activities/CommitDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/adapter/CommitNoteAdapter.java
- app/src/main/java/com/gh4a/adapter/timeline/CommentViewHolder.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/ReviewFragment.java
- app/src/main/java/com/gh4a/utils/RxUtils.java
- app/src/main/java/com/gh4a/widget/ReactionBar.java
- app/src/main/res/layout/release.xml
- app/src/main/res/menu/release.xml
- app/src/main/res/menu/release_reaction_menu.xml
- app/src/main/res/values/strings.xml
This PR implements full support for viewing and toggling reactions on releases. Here's an example:
The implementation has been harder than I initially hoped for a few reasons:
- GitHub allows to react on releases only with "positive" reactions (so no :-1: or :confused:), and that's where I started going down the rabbit hole.
The approach I chose - which to me looked the less impactful for existing logic in the ReactionBar - was to use a different menu resource for the "add reaction popup" without :-1:/:confused: items, and set up the ReactionBar use that.
However, the `AddReactionMenuHelper` wasn't designed to support showing only a subset of all possible reaction types in the menu. So I had to heavily refactor it to accommodate for that, replacing parallel arrays used to store menu items …
> Add support for release reactions

- README.md
- app/build.gradle
- app/src/main/java/com/gh4a/BaseActivity.java
- app/src/main/java/com/gh4a/BasePagerActivity.java
- app/src/main/java/com/gh4a/activities/CommitDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/DiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/IssueActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/home/HomeActivity.java
- app/src/main/java/com/gh4a/adapter/CommitNoteAdapter.java
- app/src/main/java/com/gh4a/adapter/timeline/DiffViewHolder.java
- app/src/main/java/com/gh4a/fragment/LoadingFragmentBase.java
- app/src/main/java/com/gh4a/model/TimelineItem.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
- app/src/main/java/com/gh4a/widget/OverviewRow.java
- app/src/main/java/com/gh4a/widget/ReactionBar.java
- gradle.properties
Aside from some minor dependency updates (including GH bindings), this PR introduces some tweaks to the build configuration:
- removed the [dependency info block](https://developer.android.com/build/dependencies#dependency-info-play) from the APK, which is useless for apps that aren't published on the Play Store
- migrated to [non-transitive R classes](https://developer.android.com/build/optimize-your-build#use-non-transitive-r-classes), which are now the default for new projects
- renamed the signing config for release builds to `release` (was previously named `playStore`)
- added the configuration to [remove non-English strings from built APKs via `resConfigs`](https://developer.android.com/build/shrink-code#unused-alt-resources) (will need to be updated in case a new translation is …
> Build adjustments and minor dependency updates

- app/src/main/java/com/gh4a/fragment/RepositoryFragment.java
- app/src/main/res/layout/repository.xml
- app/src/main/res/values/strings.xml
This PR adds a "Discussions" shortcut to the "Other information" section for repositories that have discussions enabled, which opens the Discussions page in a custom tab or browser.
I have decided not to put it near issues/pulls/forks etc. because it would have looked out of place, considering that there is no way to get the discussions count from the REST API.
While working on the code, I did some minor clean-ups to leverage lambdas/method references and removed some leftover dead code.
Open question: is _"Other information"_ still a good title for this section? Releases and discussions are not really "information", maybe just _"Other"_ would be a better fit?
> Add "Discussions" shortcut to repository screen

- app/src/main/assets/markdown-light.css
- app/src/main/java/com/gh4a/activities/IssueEditActivity.java
- app/src/main/java/com/gh4a/adapter/IssueLabelAdapter.java
- app/src/main/java/com/gh4a/adapter/RepositoryAdapter.java
- app/src/main/java/com/gh4a/adapter/timeline/DiffViewHolder.java
- app/src/main/java/com/gh4a/adapter/timeline/EventViewHolder.java
- app/src/main/java/com/gh4a/fragment/UserFragment.java
- app/src/main/java/com/gh4a/utils/StringUtils.java
- app/src/main/java/com/gh4a/utils/UiUtils.java
This PR fixes a few minor UI issues I've spotted throughout the app:
- there were some places where the app didn't parse emoji aliases in text (like `:smile:` or `:+1:`): user bios, label names and repository descriptions in the user/organization screen.
The only place which still lacks emoji parsing is the "Filter by label" selection screen. I've tried to implement it there too, but it broke filtering for labels with emojis because GH search filters expect the "raw" label name (with unparsed aliases). Since fixing this scenario would have required a lot more work, I've left it as is for now.
Also, while fixing repo descriptions in the user screen, I've noticed that in other repository lists there was some logic to display only the first sentence or line of the repo description. In the …
> Minor miscellaneous UI fixes

- app/src/main/java/com/gh4a/activities/RepositoryActivity.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
I have added the "Open in new window" menu item to the repository activity too, since I've found myself trying to compare two folders of different repositories but the app wasn't making it very easy :slightly_smiling_face:. I've also looked in the original PR (#784) to see if there was a reason for not adding this feature to the repository screen, but couldn't find one.
While testing this change on the emulator, I've noticed that "Open in window" was always splitting the screen and opening the activity in the bottom half, instead of just launching it as it does on my Android 10 device. It turns out that the behavior of `FLAG_ACTIVITY_LAUNCH_ADJACENT` [was changed since Android 12L](https://developer.android.com/develop/ui/views/layout/support-multi-window-mode#launch_adjacent):
>Android …
> Add ability to open repository in new window and fix behavior on Android 12L+

- app/src/main/java/com/gh4a/utils/HtmlUtils.java
This PR adds basic rendering support for [Markdown alerts](https://github.com/orgs/community/discussions/16925), a special type of blockquote that has been around for one year now.
The appearance is kept intentionally simple (no colors, no title icons) to avoid dealing with different color tones for dark/light themes and to make them visually consistent with how they appear in the WebView viewer, where they are displayed as simple blockquotes because the Markdown JS library we use doesn't yet support them.
| Before | After |
|--------|--------|
| ![alert_no_support](https://github.com/user-attachments/assets/6df9e298-f6e0-4988-8a38-602961f79160) | ![alert_with_support](https://github.com/user-attachments/assets/e3107b05-24d9-4cef-971d-7d1b7a598899) |
> Implement basic support for Markdown alerts in HTML-to-spanned conversion

- app/src/main/java/com/gh4a/adapter/NotificationAdapter.java
- app/src/main/java/com/gh4a/fragment/PullRequestConversationFragment.java
- app/src/main/java/com/gh4a/worker/NotificationsWorker.java
- app/src/main/res/drawable-night/discussion.xml
- app/src/main/res/drawable/discussion.xml
- app/src/main/res/values/strings.xml
This PR includes a couple of small changes that IMO would be worthwhile to include before the next release:
- fix a crash that occurs on PRs made by deleted users due to the `head` repository object having a `null` owner. There are several closed PRs in [azahar-emu/azahar](https://github.com/azahar-emu/azahar) repo which trigger this crash in the current version of the app.
- add an icon for discussion notifications in the notifications list (previously the app didn't show any icon for those). I've chosen to use the Material ["forum" outline icon](https://fonts.google.com/icons?selected=Material+Icons+Outlined:forum:&icon.set=Material+Icons&icon.size=24&icon.color=%231f1f1f) which is the one that most resembles [the icon used by GitHub](https://primer.style/octicons/icon/comment-discussion …
> Fix crash on PRs made by deleted users and add icon for discussion notifications

- app/src/main/java/com/gh4a/activities/CommitDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/ReleaseInfoActivity.java
- app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java
- app/src/main/java/com/gh4a/fragment/ReviewFragment.java
- app/src/main/java/com/gh4a/utils/RxUtils.java
- app/src/main/res/values/strings.xml
This PR adds more information to error snackbars when the GitHub API returns an error upon performing an action, in order to help users understand the reason without digging into the logcat:
In these cases, the "Retry" button - which is almost always useless for API errors - is replaced by "Copy error message", which should make it easy to get the full message when reporting an issue or when it's too long to fit in the snackbar, as it's the case with OAuth restriction errors:
When an action fails due to a non-API error, the usual "Retry" button is displayed instead, but the message has been reworded to make it clear that it's most likely a connectivity issue (which should be the only other likely cause of errors, unless we have a bug in the code).
Let me know your thoughts!
> Display more helpful error messages in snackbars

- app/src/main/java/com/gh4a/activities/CommitActivity.java
- app/src/main/java/com/gh4a/activities/DiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/WikiActivity.java
- app/src/main/java/com/gh4a/adapter/CommitCommentAdapter.java
- app/src/main/java/com/gh4a/fragment/CommitCommentsFragment.java
- app/src/main/java/com/gh4a/fragment/CommitFragment.java
- app/src/main/java/com/gh4a/fragment/CommitNoteFragment.java
- app/src/main/java/com/gh4a/utils/IntentUtils.java
The main goal of this PR is to fix a crash that occurs when switching away from the commit activity when the commit has many comments (such as https://github.com/git/git/commit/e83c5163316f89bfbde7d9ab23ca2e25604af290 with almost 300 comments), caused by a `TransactionTooLargeException` due to the comments being saved in the fragment args `Bundle` (and then stored in the saved instance state by Android) without compression.
However, I've ended up heavily refactoring the code for compressing args in `Bundle`s/`Intent` extras because otherwise I would have introduced more duplication. In summary:
- I've made the compression/decompression functions able to work with any kind of object supported by `Parcel`s, so that we don't need to have a different function for each type of object we want …
> Fix crash on commits with many comments and refactor compression in bundle

- app/src/main/java/com/gh4a/activities/CommitDiffViewerActivity.java
- app/src/main/java/com/gh4a/activities/PullRequestDiffViewerActivity.java
- app/src/main/java/com/gh4a/resolver/CommitCommentLoadTask.java
- app/src/main/java/com/gh4a/resolver/CommitDiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/DiffLoadTask.java
- app/src/main/java/com/gh4a/resolver/LinkParser.java
- app/src/main/java/com/gh4a/resolver/PullRequestDiffLoadTask.java
- app/src/main/java/com/gh4a/utils/ApiHelpers.java
- app/src/test/java/com/gh4a/resolver/LinkParserTest.java
While working on #1458, I noticed that the app handled diff URLs on PRs/commits and commit comment URLs incorrectly:
- URLs to diff lines in commits and PRs (those ending in `#diff-<hash>`) were being parsed as if the hash were the MD5 sum of the path, but the hash has been changed to be a SHA256 for a while now (at least since 2021 according to [some comments on StackOverflow](https://stackoverflow.com/questions/43996083/extraction-of-diff-hash-from-github-commit-url/69177495#69177495)) - fixed in d943b931
- the app incorrectly treated URLs ending in `#commitcomment-<id>` as URLs to comments _on the commit_ **or** to comments _on the commit diff_, but they can only be the former (fixed in 2300ddad84). The latter URLs always end in `#r<id>` instead (I suppose that GH changed them at some …
> Fix handling of diff and commit comment URLs

- app/src/main/java/com/gh4a/activities/CommitHistoryActivity.java
- app/src/main/java/com/gh4a/activities/FileViewerActivity.java
- app/src/main/java/com/gh4a/fragment/CommitListFragment.java
- app/src/main/java/com/gh4a/fragment/ContentListFragment.java
- app/src/main/res/menu/commit_history_menu.xml
- app/src/main/res/values/strings.xml
> Allow following file renames in commit history activity
